// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/wallet/chain/c (interfaces: EthKeychain)
//
// Generated by this command:
//
//	mockgen -destination=mocks/keychain/mock_ethkeychain.go -package=mocks github.com/ava-labs/avalanchego/wallet/chain/c EthKeychain
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	keychain "github.com/ava-labs/avalanchego/utils/crypto/keychain"
	set "github.com/ava-labs/avalanchego/utils/set"
	common "github.com/ava-labs/libevm/common"
	gomock "go.uber.org/mock/gomock"
)

// MockEthKeychain is a mock of EthKeychain interface.
type MockEthKeychain struct {
	ctrl     *gomock.Controller
	recorder *MockEthKeychainMockRecorder
	isgomock struct{}
}

// MockEthKeychainMockRecorder is the mock recorder for MockEthKeychain.
type MockEthKeychainMockRecorder struct {
	mock *MockEthKeychain
}

// NewMockEthKeychain creates a new mock instance.
func NewMockEthKeychain(ctrl *gomock.Controller) *MockEthKeychain {
	mock := &MockEthKeychain{ctrl: ctrl}
	mock.recorder = &MockEthKeychainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthKeychain) EXPECT() *MockEthKeychainMockRecorder {
	return m.recorder
}

// EthAddresses mocks base method.
func (m *MockEthKeychain) EthAddresses() set.Set[common.Address] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthAddresses")
	ret0, _ := ret[0].(set.Set[common.Address])
	return ret0
}

// EthAddresses indicates an expected call of EthAddresses.
func (mr *MockEthKeychainMockRecorder) EthAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthAddresses", reflect.TypeOf((*MockEthKeychain)(nil).EthAddresses))
}

// GetEth mocks base method.
func (m *MockEthKeychain) GetEth(addr common.Address) (keychain.Signer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEth", addr)
	ret0, _ := ret[0].(keychain.Signer)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetEth indicates an expected call of GetEth.
func (mr *MockEthKeychainMockRecorder) GetEth(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEth", reflect.TypeOf((*MockEthKeychain)(nil).GetEth), addr)
}
