name: awm-relayer
services:
  awm-relayer:
    image: avaplatform/awm-relayer:{{ .AWMRelayerVersion }}
    container_name: awm-relayer
    restart: unless-stopped
    user: "1000:1000"  # ubuntu user
    volumes:
      - /home/ubuntu/.awm-relayer:/.awm-relayer:rw
    command: 'awm-relayer --config-file /.awm-relayer/awm-relayer-config.json'
